#!/usr/bin/env python
import sys
import socket

from taskit.common import STOP, KILL, STATUS
from port_expander import get_ports


COMMANDS = {'stop': (STOP, 'stopped'), 'kill': (KILL, 'terminated'), 
            'status': (STATUS, 'up, %s jobs running')}


def send_msg(host, msg, note):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect(host)
        sock.send(msg)
    except socket.error:
        return 'down'
    
    if '%s' in note:
        res = sock.recv(2048).decode()
    else:
        res = ()
    
    sock.close()
    
    return note % res


def main():
    command, host, ports = sys.argv[1:]
    command = COMMANDS[command]
    for port in get_ports(ports):
        res = send_msg((host, port), *command)
        print('%s:%s --> %s' % (host, port, res))


if __name__ == '__main__':
    main()
